[package]
name = "TestRust"
version = "0.1.0"
authors = ["Salem Yaslem <xlmnxp@outlook.sa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
